// Generated by https://quicktype.io

export interface DashboardSummaryResponse {
    numberOfOrders:                   number;
    paidOrders:                       number;
    notPaidOrders:                    number;
    numberOfClients:                  number;
    numberOfProducts:                 number;
    numberOfProductsWithNoInventory:  number;
    numberOfProductsWithLowInventory: number;
}
